### ISSUE TITLE
Where can I find the "Release Template name" for a given Release Management setup?

### ISSUE THREAD

**Issue by jpierson** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#22]
I'm migrating assets that I have little information about so I'm stuck at running the `RMWorkflowMigrator.exe` tool because I don't know what to feed in for the -t parameter to specify the Release Template name. I don't have the desktop tool installed to see the info at the moment and I'd rather not install if unless there is no other way to find a list of the release template names. Looking at the database I see a concept of Release Paths but when I tried those names I received a generic `The release template "MY RELEASE PATH NAME" has no stages. Check that the release template name is spelled correctly.` error.

**Comment by DanielBMann9000** [comment]
You can look at the `ApplicationVersion` table to find release template names. Why it's named that, I can't say. It wouldn't be very difficult to add a command line flag to list release template names, but I think the most common scenario is that someone has access to the RM client.
