### ISSUE TITLE
Not really in issue but a question

### ISSUE THREAD

**Issue by crshnbrn66** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#25]
Does this tool leave the Existing Release management tool database intact? Doesn't change anything?
I assume it just does a "get" and no put or other things to change the existing Release management database?

**Comment by wpschaub** [comment]
The tool only queries the RM DB to generate the release scripts.
It makes no changes to the source or target environments.

**Comment by crshnbrn66** [comment]
Perfect.
