### ISSUE TITLE
RMWorkflowMigrator error: Version 14.98.25331.0 is unsupported

### ISSUE THREAD

**Issue by mattsteinRRD** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#26]
When I run RMWorkflowMigrator against our on-premises TFS 2015 Update 3 install, I get "A critical error occurred:" with message, "Version 14.98.25331.0 is unsupported."

**Comment by DanielBMann9000** [comment]
Whoops. Nothing changed in Update 3 that would impact the tool, so I just took the assembly version number from the installer and updated the tool to support that version. Obviously, it's not correct. We'll put out an updated version shortly, in the meantime you can update the version number strings in `Program.cs` to support Update 3 and rebuild from source.
