### ISSUE TITLE
Overwrites scripts generated from stage 1 with the ones generated from stage 2. 

### ISSUE THREAD

**Issue by wpschaub** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#4]
It overwrote the scripts that got generated from stage 1 with the one that got generated from stage.
Email: Feedback on "Release management workflow migrator", 2015-12-15

**Comment by DanielBMann9000** [comment]
This is a scenario where the behavior was absolutely what was intended, but it's not good behavior.

The behavior was this: Scripts are dumped into whatever output folder you specify. Better behavior would be to put the scripts into subfolders corresponding to the release template/stage being extracted.

That better behavior was implemented in commit 4763dd93ad18d0f32af1a83128883f8697378ca8
