### ISSUE TITLE
 Neither generated the powershell scripts nor failed for a vNext template

### ISSUE THREAD

**Issue by wpschaub** [ALM-Rangers/Migrate-assets-from-RM-server-to-VSTS#6]
Does it support vNext release templates as it neither generated the PowerShell scripts nor failed for a vNext template?
Email: Feedback on "Release management workflow migrator", 2015-12-15

**Comment by DanielBMann9000** [comment]
Fixed in commit dadece1167b8d7838d224a8bd42589e50e03dd52
